### PR TITLE
Rachael profile

### PR DESCRIPTION
**Pull request by RachaelMurray**
Added a pic to assets and a page to teams (well, I tried to).

### CODE REVIEW

**Comment by RachaelMurray** [comment]
My photo file size might be too large, let me know if it's a problem.

**Comment by ewallace** [comment]
The page looks great! A smaller photo would be better, yes.

Could you add "rmm" or something like that as "handle"? Basically that makes it easier to reference you from other parts of the site.

If you can make these updates, I'll merge to staging.

**Comment by RachaelMurray** [comment]
What is a handle and how can I add one?

**Comment by ewallace** [comment]
Sorry I wasn't clear! Look at the header information in the markdown file, that has lines like 

```
---
layout: member
title: "Edward W. J. Wallace"
position: Group Leader
nickname: Edward
handle: ew
...
```

I was asking if you could populate the fields for `handle`, and why not add `nickname` and `github` as well?

**Comment by RachaelMurray** [comment]
I see! No problem.

**Comment by ewallace** [comment]
Brilliant, accepting pull request!

**Comment by ewallace** [comment]
Good work! I made a couple of small changes, updating the pic filename, and removing a space so that the EASTBIO link worked. Should be live now.

**Pull request merged**
