### PR TITLE
Inclusivity statement

### PR DESCRIPTION
**Pull request by marahjn**

### CODE REVIEW

**Comment by ewallace** [comment]
I think the statement is great.

Which page does it belong on, on the website?

**Comment by marahjn** [comment]
> I think the statement is great.
> 
> Which page does it belong on, on the website?

We want it to stay visible and as a clear statement about our values, and I think that fits best within the team page. So if we were to add it to an existing page such as Team, we can have it as a statement at the top/middle of that page. Alternatively, we can make a separate page for it. What do you think?

**Comment by ewallace** [comment]
At the moment the team page is mostly a "faceboard" and I don't know how to do the reformatting to put the diversity statement somewhere sensible on that. If someone can figure that out...

Maybe it would belong on [about](https://ewallace.github.io/about.html) - which could be reorganised anyway. I just updated that page including a little on diversity and how to write to me/us.

Or maybe we can put it on the main page?

What would you think about a "blog post" to talk about why we are writing a diversity statement, etc.

One last point - can we stick to dates as `yyyy-mm-dd`.

**Comment by ewallace** [comment]
The statement looks great, we still need to figure out the formatting.

@marahjn, could you find a time to meet with @FlicAnderson, in the next 2-3 weeks, to discuss markdown format and putting this statement on the `about` page?

**Comment by marahjn** [comment]
> The statement looks great, we still need to figure out the formatting.
> 
> @marahjn, could you find a time to meet with @FlicAnderson, in the next 2-3 weeks, to discuss markdown format and putting this statement on the `about` page?

Yeah sure, I'll set up a time with @FlicAnderson to talk about this!

**Comment by ewallace** [comment]
Thanks so much @marahjn and sorry for the ridiculous delay!

This was updated and added to the about page in [/misc/_posts/](https://github.com/ewallace/ewallace.github.io/tree/master/misc/_posts), in commit ab291bb.

**Pull request closed without merging**
