### PR TITLE
add Marah's favourite paper 

### PR DESCRIPTION
**Pull request by marahjn**
Add Marah's favourite paper to blog 2020-11-26-favourite-papers.md

### CODE REVIEW

**Review by FlicAnderson — COMMENTED** [review]
Great!

The `###` line can perhaps be deleted once merged, because this would be used to denote a heading, and I'm not sure what the best heading for this paper would be. @marahjn do you have any suggestions? I was thinking it would be good to group the papers by area/type, does anything fit this paper?

**Comment by marahjn** [comment]
> Great!
> 
> The `###` line can perhaps be deleted once merged, because this would be used to denote a heading, and I'm not sure what the best heading for this paper would be. @marahjn do you have any suggestions? I was thinking it would be good to group the papers by area/type, does anything fit this paper?

I intentionally left it there because I couldn't think of a heading to appropriately describe it, and I thought Edward might have a good idea. All I can think of is "Cell Biology" which is probably too broad.

**Comment by ewallace** [comment]
Looks cool! For a header, what about "High Throughput Genetics and Cell Biology"? That makes it sound cooler than just "Cell Biology".

**Comment by marahjn** [comment]
Thanks @ewallace ! "High Throughput Genetics and Cell Biology" sounds like a cool heading, I edited the post and committed the change (I hope I did this right).

**Pull request merged**
